### ISSUE TITLE
demo3_1.m - numerical underflow issues for large sample sizes & variances less than 1

### ISSUE THREAD

**Issue by gborrageiro** [avehtari/BDA_m_demos#1]
hi,

I am seeing numerical underflow issues when there are large sample sizes (> 1000 for example) and for data who's variances are < 1.
Any chance you could generalize your function scripts to cope with such situations?

thanks
Gabriel

**Comment by avehtari** [comment]
Thanks for reporting this. This is an excellent example of underflow issue and instead of fixing it, we'll add a note that it is possible to observe this problem with the values you mentioned! If you need a more robust code for other purposes, please let us know.

**Comment by gborrageiro** [comment]
Thx Ali, a more robust version would be great.
